name: gestion_actividades
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^0.13.4
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  google_fonts: ^2.3.1
  firebase_auth: ^3.3.7
  firebase_database: ^9.0.8
  table_calendar: ^3.0.4
  calendar_appbar: ^0.0.6
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  fonts:
    - family: CleanSports
      fonts:
        - asset: assets/fonts/CleanSports.ttf
          weight: 400
    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400

  assets:
    - assets/images/pictograma.png
    - assets/images/logoApp.png
    - assets/images/ejercicio.png
    - assets/images/entrenador.png
    - assets/images/chico.png
    - assets/images/chica.png